# I wouldn't recommend making changes in this config unless you're sure of what you're doing
# for easier access to these settings, try using /emoji settings
# The reason why I say this is because not all settings are visible in here unless you make changes
# to them directly in the /emoji settings GUI (so redundant information is not stored)

# Resource URL: https://www.spigotmc.org/resources/chatemojis.88027/
# For bug/glitch reports, suggestions, or support please do so on my github repository
# Github URL: https://github.com/Mxlvin/ChatEmojis

# List of supported languages can be found on Github
lang: en_US

settings:
  use:
    chat:
      enabled: true
    signs:
      enabled: true
    books:
      enabled: true